/*
This file contains all constants in the app.
*/

module.exports = {
	// PERSISTENCE
	FIREBASE: "https://valcase.firebaseio.com/",

	// AUTH STATES
	LOGGED_IN: "LOGGED_IN",
	ANONYMOUS: "ANONYMOUS",
	AWAITING_AUTH_RESPONSE: "AWAITING_AUTH_RESPONSE",

	// AUTH ACTIONS
	ATTEMPTING_LOGIN: "ATTEMPTING_LOGIN",
	LOGIN_USER: "LOGIN_USER",
	LOGOUT: "LOGOUT",

	// POLL ACTIONS
	AWAIT_POLL_RESPONSE: "AWAIT_POLL_RESPONSE",
	RECEIVE_POLL_RESPONSE: "RECEIVE_POLL_RESPONSE",
	RECEIVE_POLL_UPDATE: "RECEIVE_POLL_UPDATE"
	
};