/*
This file contains all constants in the app.
*/

module.exports = {
	// PERSISTENCE
	FIREBASE: "https://valcase.firebaseio.com/",

	// AUTH STATES
	LOGGED_IN: "LOGGED_IN",
	ANONYMOUS: "ANONYMOUS",
	AWAITING_AUTH_RESPONSE: "AWAITING_AUTH_RESPONSE",

	// AUTH ACTIONS
	ATTEMPTING_LOGIN: "ATTEMPTING_LOGIN",
	LOGIN_USER: "LOGIN_USER",
	LOGOUT: "LOGOUT",

	// MOOD STATES
	UPDATING_MOOD: "UPDATING_MOOD",

	// MOOD ACTIONS
	CHANGE_MOOD: "CHANGE_MOOD",
	RECEIVE_COMPANY_MOOD_UPDATE: "RECEIVE_COMPANY_MOOD_UPDATE"
};