/*
This file contains all constants in the app.
*/

module.exports = {
	// UI FEEDBACK
	DISPLAY_ERROR: "DISPLAY_ERROR",
	DISPLAY_SUCCESS: "DISPLAY_SUCCESS",

	// PERSISTENCE
	FIREBASE: "https://valcase.firebaseio.com/",

	// AUTH STATES
	LOGGED_IN: "LOGGED_IN",
	ANONYMOUS: "ANONYMOUS",
	AWAITING_AUTH_RESPONSE: "AWAITING_AUTH_RESPONSE",

	// AUTH ACTIONS
	ATTEMPTING_LOGIN: "ATTEMPTING_LOGIN",
	LOGIN_USER: "LOGIN_USER",
	LOGOUT: "LOGOUT",

	// POLL ACTIONS
	AWAIT_POLL_RESPONSE: "AWAIT_POLL_RESPONSE",
	RECEIVE_POLL_RESPONSE: "RECEIVE_POLL_RESPONSE",
	RECEIVE_POLL_UPDATE: "RECEIVE_POLL_UPDATE",

	// CHAT ACTIONS
	RECEIVE_CHAT_UPDATE: "RECEIVE_CHAT_UPDATE",
	AWAIT_CHAT_RESPONSE: "AWAIT_CHAT_RESPONSE",
	RECEIVE_CHAT_RESPONSE: "RECEIVE_CHAT_RESPONSE",

	MAX_CHATS: 20,
	MIN_CHAT_LENGTH: 1,

	// USER ACTIONS
	RECEIVE_USER_DATA: "RECEIVE_USER_DATA",
	AWAIT_USER_RESPONSE: "AWAIT_USER_RESPONSE",
	RECEIVE_USER_RESPONSE: "RECEIVE_USER_RESPONSE"
};